'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PokemonBattleOnline.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property female() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("female", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hailstrom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hailstrom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HailstromBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HailstromBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HpColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HpColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HPLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HPLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property male() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("male", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mew() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("mew", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MoveFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MoveFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmball2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmball2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmball2b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmball2b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmball2c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmball2c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmballb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmballb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmballc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmballc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PMState1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMState1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PMState2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMState2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PMState3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMState3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pokemon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pokemon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PokemonBall() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PokemonBall", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property PokemonFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PokemonFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rainy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rainy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RainyBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RainyBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectMove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectMove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectPokemon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectPokemon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectTarget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectTarget", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SubBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SubBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Substitute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Substitute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sunny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sunny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SunnyBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SunnyBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 中毒() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("中毒", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 冻结() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("冻结", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 岩山() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("岩山", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 平地() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("平地", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 建筑() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("建筑", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 水域() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("水域", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 沙地() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("沙地", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 洞窟() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("洞窟", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 烧伤() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("烧伤", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 睡眠() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("睡眠", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 草丛() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("草丛", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 雪原() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雪原", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 麻痹() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("麻痹", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
